export const prods = [
{id:1,
name:'classic chair',
price:60,
img:'product-1.png',
description:'classic chair Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis orci eu accumsan feugiat. Sed suscipit ornare massa, quis vestibulum risus pellentesque id. Praesent vestibulum efficitur ipsum vitae vestibulum. Nulla est sem'},
{id:2,
name:'royal chair',
price:95,
img:'product-2.png',
description:'royal chair Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis orci eu accumsan feugiat. Sed suscipit ornare massa, quis vestibulum risus pellentesque id. Praesent vestibulum efficitur ipsum vitae vestibulum. Nulla est sem'},
{id:3,
name:'rocker chair',
price:70,
img:'product-3.png',
description:'rocker chair Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis orci eu accumsan feugiat. Sed suscipit ornare massa, quis vestibulum risus pellentesque id. Praesent vestibulum efficitur ipsum vitae vestibulum. Nulla est sem'},
{id:4,
name:'desk chair',
price:75 ,
img:'product-4.png',
description:'desk chair Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis orci eu accumsan feugiat. Sed suscipit ornare massa, quis vestibulum risus pellentesque id. Praesent vestibulum efficitur ipsum vitae vestibulum. Nulla est sem'},
{id:5,
name:' leather couch',
price:130,
img:'product-5.png',
description:'leather couch Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis orci eu accumsan feugiat. Sed suscipit ornare massa, quis vestibulum risus pellentesque id. Praesent vestibulum efficitur ipsum vitae vestibulum. Nulla est sem'},
{id:6,
name:'single couch',
price:145,
img:'product-6.png',
description:'single couch Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis orci eu accumsan feugiat. Sed suscipit ornare massa, quis vestibulum risus pellentesque id. Praesent vestibulum efficitur ipsum vitae vestibulum. Nulla est sem'},
{id:7,
name:'white bookcase',
price:150,
img:'product-7.png',
description:'white bookcase Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis orci eu accumsan feugiat. Sed suscipit ornare massa, quis vestibulum risus pellentesque id. Praesent vestibulum efficitur ipsum vitae vestibulum. Nulla est sem'},
{id:8,
name:'black table',
price:110,
img:'product-8.png',
description:'black table Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis orci eu accumsan feugiat. Sed suscipit ornare massa, quis vestibulum risus pellentesque id. Praesent vestibulum efficitur ipsum vitae vestibulum. Nulla est sem'},
{id:9,
name:'triple couch sofa',
price:225,
img:'product-9.png',
description:'couch sofa Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis orci eu accumsan feugiat. Sed suscipit ornare massa, quis vestibulum risus pellentesque id. Praesent vestibulum efficitur ipsum vitae vestibulum. Nulla est sem'},
{id:10,
name:'wooden desk ',
price:95,
img:'product-10.png',
description:'wooden desk Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis orci eu accumsan feugiat. Sed suscipit ornare massa, quis vestibulum risus pellentesque id. Praesent vestibulum efficitur ipsum vitae vestibulum. Nulla est sem'},
{id:11,
name:'wooden tv stand',
price:180,
img:'product-11.png',
description:'wooden tv stand Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis orci eu accumsan feugiat. Sed suscipit ornare massa, quis vestibulum risus pellentesque id. Praesent vestibulum efficitur ipsum vitae vestibulum. Nulla est sem'},
{id:12,
name:'xl couch sofa',
price:300,
img:'./product-12.png',
description:'couch sofa Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis orci eu accumsan feugiat. Sed suscipit ornare massa, quis vestibulum risus pellentesque id. Praesent vestibulum efficitur ipsum vitae vestibulum. Nulla est sem'}
];